### ISSUE TITLE
Sync timer between clients and server

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [pesto-students/batch-6-chess-multiplayer#64]
Initial proposal is to have server keep the time and clients ask for the time from server.
We already use sockets to get moves, we can send time too.
If sending time very frequently is overkill, we can send it every time there is a move.

@chirag-shinde @sagarbakhtar @codemayank

Please add solution proposals, so that we can evaluate them and start with development.

**Comment by Prabhakar-Poudel** [comment]
Couple of issues I have seen so far:

1) timer continued running even after game over. SS below
2) loosing player was declared winner. SS below

![bwon](https://user-images.githubusercontent.com/20899846/57330687-68ae4400-7134-11e9-9159-6730a8ea1580.png)

3) only one player's timer is running all the time:
![buggy timer](https://user-images.githubusercontent.com/20899846/57330810-b9be3800-7134-11e9-9308-864522839f41.png)

**Comment by codemayank** [comment]
These are due to both clients timers not being in sync.

**Comment by codemayank** [comment]
We can have a single timer on the server. The clients can listen to this timer and display the time.

**Comment by codemayank** [comment]
One way to implement the initial proposal will be to emit a timer event every second using setInterval. The clients can listen to this event and display the time.

**Comment by Prabhakar-Poudel** [comment]
> One way to implement the initial proposal will be to emit a timer event every second using setInterval. The clients can listen to this event and display the time.

That does not seem optimal solution.
After the client receives a time ( unless server acknowledges a move, the player's time continues to reduce), hence we can loosely say that time is directly related to move, and we need to care only about flipping timers per move.
That being much efficient will lead to a number of issues when connection is lost and other such issues, but it will hold the same when sending timers per second also.

**Comment by codemayank** [comment]
> > One way to implement the initial proposal will be to emit a timer event every second using setInterval. The clients can listen to this event and display the time.
> 
> That does not seem optimal solution.
> After the client receives a time ( unless server acknowledges a move, the player's time continues to reduce), hence we can loosely say that time is directly related to move, and we need to care only about flipping timers per move.
> That being much efficient will lead to a number of issues when connection is lost and other such issues, but it will hold the same when sending timers per second also.

I Guess what you are saying here is we keep the existing setup of maintaining the timers on the client and flip the timers every time a move event occurs.

The problem with this approach is that there is no single source of truth for the time as both clients keep their own time, and clients can increase their times to keep on playing well beyond the time limit.

One way to solve this would be to calculate the time taken for each move on the server and keep substracting this time from the time left for each player. Also, we have to send the time left to the clients every time a move event occurs so that both clients display the same time.
