### ISSUE TITLE
Add navigation bar

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [pesto-students/batch-6-chess-multiplayer#83]
After login, we need the logout button to be in a navigation bar. Eventually, we will use it for user options also.

**Comment by sagarbakhtar** [comment]
This is being handled in this #79 PR

**Comment by Prabhakar-Poudel** [comment]
Please close this once merged. @sagarbakhtar

**Comment by Prabhakar-Poudel** [comment]
Done #104
