### ISSUE TITLE
Fix chess square Height.

### ISSUE THREAD

**Issue by codemayank** [pesto-students/batch-6-chess-multiplayer#95]
![chess_square_height](https://user-images.githubusercontent.com/13509968/57735375-015b3b80-76c2-11e9-90f0-90284481d284.png)

**Comment by Prabhakar-Poudel** [comment]
For issues like this please add more details.
Like this one is mobile only IIRC?

**Comment by codemayank** [comment]
> For issues like this please add more details.
> Like this one is mobile only IIRC?

Ok, will keep in mind. Although this issue is for all display sizes, it's only apparent in the mobile view.
