### ISSUE TITLE
Add links in nav bar

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [pesto-students/batch-6-chess-multiplayer#99]
Missing links:
* Leaderboard
* Home/dashboard

Optionally, handle the case where the user clicks any link in the middle of the game.
Should he lose? Should the socket connection removed? Should he be prompted before redirecting?
If not handling this case, create a new issue for it and link it here before merging any related PR.

**Comment by sagarbakhtar** [comment]
Adding navigation in this issue
Created new issue (#102 ) for socket connection issue
